// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDspmYK924QnX4q2-_vqVSlscf_u4i5XtE',
    appId: '1:309490674400:web:04a393adc8ae52b5903e85',
    messagingSenderId: '309490674400',
    projectId: 'travelpal-muntinlupa',
    authDomain: 'travelpal-muntinlupa.firebaseapp.com',
    storageBucket: 'travelpal-muntinlupa.firebasestorage.app',
    measurementId: 'G-Y1WZXW2ET2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7WR9z29zBFNAcekHbuiDku2kwMdTj50',
    appId: '1:309490674400:android:450b9e1c55a6eba7903e85',
    messagingSenderId: '309490674400',
    projectId: 'travelpal-muntinlupa',
    storageBucket: 'travelpal-muntinlupa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIf4JZziAb-Bl6kVYf84o3rGaegM4nhHg',
    appId: '1:309490674400:ios:574694a080de4eaf903e85',
    messagingSenderId: '309490674400',
    projectId: 'travelpal-muntinlupa',
    storageBucket: 'travelpal-muntinlupa.firebasestorage.app',
    iosBundleId: 'com.example.travelpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIf4JZziAb-Bl6kVYf84o3rGaegM4nhHg',
    appId: '1:309490674400:ios:574694a080de4eaf903e85',
    messagingSenderId: '309490674400',
    projectId: 'travelpal-muntinlupa',
    storageBucket: 'travelpal-muntinlupa.firebasestorage.app',
    iosBundleId: 'com.example.travelpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDspmYK924QnX4q2-_vqVSlscf_u4i5XtE',
    appId: '1:309490674400:web:b304497d583f3a86903e85',
    messagingSenderId: '309490674400',
    projectId: 'travelpal-muntinlupa',
    authDomain: 'travelpal-muntinlupa.firebaseapp.com',
    storageBucket: 'travelpal-muntinlupa.firebasestorage.app',
    measurementId: 'G-K1XSKYZ19Z',
  );
}
